In [1]:
# install.packages("Rcpp")

In [2]:
library(Rcpp)

Warning message:
"package 'Rcpp' was built under R version 3.6.3"

#### 1. Calculate Squared Distance

$D = dist2(X, C)$ takes two matrices of vectors and calculates the squared Euclidean distance between them.  Both matrices must be of the same column dimension.  If $X$ has $M$ rows and $N$ columns, and $C$ has $L$ rows and $N$ columns, then the result has $M$ rows and $L$ columns.  The $i$, $j$th entry is the  squared distance from the $i$th row of $X$ to the $j$th row of $C$.

In [3]:
dist2 <- function(x, c) {
    # Get the number of data points and dimensions in x
    ndata <- nrow(x)
    dimx <- ncol(x)
    
    # Get the number of centres and dimensions in c
    ncentres <- nrow(c)
    dimc <- ncol(c)
    
    # Check that the dimensions of x and c match
    if (dimx != dimc) {
        stop("Data dimension does not match dimension of centres")
    }
    
    # Calculate the squared Euclidean distance between each data point in x and each centre in c
    n2 <- matrix(0, nrow = ndata, ncol = ncentres)
    for (i in 1:ncentres) {
        n2[, i] <- colSums((t(x) - t(c)[,i])^2)
    }
    
    #n2 <- matrix(rowSums(x^2), ndata, 1) %*% matrix(rep(1, ncentres), ncol = ncentres) + 
    #      matrix(rep(rowSums(c), ndata), ncol = ncentres, byrow = TRUE) -
    #      2 * x %*% t(c)
    
    # Return the squared Euclidean distance matrix
    return(n2)
}

In [4]:
# install.packages('fields')

In [5]:
set.seed(1)
x <- matrix(rnorm(2*3, mean=2, sd=2), nrow=2)
c <- matrix(runif(5*3), nrow=5)

# Use r built-in distance function to check if the above calculation is correct
library(fields)
print(paste0('Number of different elements from two distance matrices calculated is ', sum((round(dist2(x, c),2) == round(rdist(x,c)^2, 2)) == FALSE)))

Warning message:
"package 'fields' was built under R version 3.6.3"Loading required package: spam
Warning message:
"package 'spam' was built under R version 3.6.3"Loading required package: dotCall64
Warning message:
"package 'dotCall64' was built under R version 3.6.3"Loading required package: grid
Spam version 2.6-0 (2020-12-14) is loaded.
Type 'help( Spam)' or 'demo( spam)' for a short introduction 
and overview of this package.
Help for individual functions is also obtained by adding the
suffix '.spam' to the function name, e.g. 'help( chol.spam)'.

Attaching package: 'spam'

The following objects are masked from 'package:base':

    backsolve, forwardsolve

See https://github.com/NCAR/Fields for
 an extensive vignette, other supplements and source code 


[1] "Number of different elements from two distance matrices calculated is 0"


#### 2. Cost Function

In [6]:
hist_cost_2 <- function(BH1, BH2, eps=0.001) {
    # same as hist_cost.m but BH1 and BH2 can be of different lengths
    nsamp1 <- dim(BH1)[1]
    nbins <- dim(BH1)[2]
    nsamp2 <- dim(BH2)[1]
    
    BH1n <- BH1 / matrix(rep(rowSums(BH1)+eps, nbins), nrow=nsamp1, byrow=F)
    BH2n <- BH2 / matrix(rep(rowSums(BH2)+eps, nbins), nrow=nsamp2, byrow=F)
    
    tmp1 <- array(rep(BH1n, each=nsamp2), dim=c(nsamp1, nsamp2, nbins))
    tmp2 <- array(rep(t(BH2n), each=nsamp1), dim=c(nsamp1, nsamp2, nbins))
    
    HC <- 0.5 * apply((tmp1 - tmp2)^2 / (tmp1 + tmp2 + eps), c(1, 2), sum)
    return(HC)
}

#### 3. Sample Sequence from Designated Points

In [7]:
# Sample sequence from designated points
# Given: the sequence of feature points
# Return: subsequences
samplingSequencesIdx <- function(sensordata, seqlen, idx) {
  # Check if the correct number of arguments have been provided
  if(missing(idx)) {
    stop("Insufficient number of arguments")
  }
  
  # Get the number of timestamps and dimensions
  nTimeStamps <- nrow(sensordata)
  nDims <- ncol(sensordata)
  
  # Check if the input matrix is in the correct format
  if(nTimeStamps < nDims) {
    warning("Synchronized signals should be arranged column-wisely\n")
  }
  
  # Initialize variables
  mask <- 1:seqlen
  mask <- mask - ceiling(seqlen/2)
  nSeqs <- length(idx)
  sequences <- list()
  tAnchor <- idx
  cnt <- 0
  
  # Loop through each subsequence
  for(i in 1:nSeqs) {
    iloc <- idx[i]
    imask <- mask + iloc
    
    # Check if the subsequence is within the bounds of the input matrix
    if(imask[1] <= 0 && imask[length(imask)] <= nTimeStamps) {
      tmp <- matrix(rep(sensordata[1, ], (1-imask[1])*nDims), ncol=nDims, byrow=TRUE)
      isequence <- rbind(tmp, sensordata[1:imask[length(imask)], ])
    } 
    else if(imask[length(imask)] > nTimeStamps && imask[1] >= 1) {
      tmp <- matrix(rep(sensordata[nTimeStamps, ], (imask[length(imask)]-nTimeStamps)*nDims), ncol=nDims, byrow=TRUE)
      isequence <- rbind(sensordata[imask[1]:nTimeStamps, ], tmp)
    } 
    else if(imask[1] <= 0 && imask[length(imask)] > nTimeStamps) {
      tmp1 <- matrix(rep(sensordata[1, ], (1-imask[1])*nDims), ncol=nDims, byrow=TRUE)
      tmp2 <- matrix(rep(sensordata[nTimeStamps, ], (imask[length(imask)]-nTimeStamps)*nDims), ncol=nDims, byrow=TRUE)
      isequence <- rbind(tmp1, sensordata, tmp2)
    } 
    else {
      isequence <- sensordata[imask, ]
    }
    
    cnt <- cnt + 1
    tAnchor[cnt] <- iloc
    sequences <- rbind(sequences, list(isequence))
  }
  
  tAnchor <- tAnchor[1:cnt]
  
  return(list(sequences, tAnchor))
}

In [8]:
# Read data from file
data_urc <- read.table('../../data/dataSet_URC.txt', quote="\"", comment.char="")[,2:10]
samplingSequencesIdx(data_urc, 5, c(3:5))

[[1]]
     [,1]  
[1,] List,9
[2,] List,9
[3,] List,9

[[2]]
[1] 3 4 5

#### 4. Dynamic Programming

In [9]:
sourceCpp("dpcore.cpp")

In [10]:
# [p,q,D,sc] = dpfast(M,C,T,G)
#    Use dynamic programming to find a min-cost path through matrix M.
#    Return state sequence in p,q; full min cost matrix as D and 
#    local costs along best path in sc.
#    This version gives the same results as dp.m, but uses dpcore.mex
#    to run ~200x faster.
#    C is a step matrix, with rows (i step, j step, cost factor)
#    Default is [1 1 1.0;0 1 1.0;1 0 1.0];
#    Another good one is [1 1 1;1 0 1;0 1 1;1 2 2;2 1 2]
#    T selects traceback origin: 0 is to any edge; 1 is top right (default);
#    T > 1 finds path to min of anti-diagonal T points away from top-right.
#    Optional G defines length of 'gulleys' for T=0 mode; default 0.5
#    (i.e. accept path to only 50% of edge nearest top-right)
# 2003-04-04,2005-04-04 dpwe@ee.columbia.edu $Header: /Users/dpwe/projects/dtw/RCS/dpfast.m,v 1.6 2008/03/14 14:40:50 dpwe Exp dpwe $
  
  # Copyright (c) 2003 Dan Ellis <dpwe@ee.columbia.edu>
  # released under GPL - see file COPYRIGHT

dpfast <- function(M, C=c(1,1,1.0), T=1, G=0.5) {
    if (missing(M)) {
        stop("Error: M is missing")
    }
    
    # Default step / cost matrix
    if (missing(C)) {
        C = matrix(c(1, 1, 1.0, 0, 1, 1.0, 1, 0, 1.0), ncol=3, byrow=TRUE)
    }
    
    # Default: path to top-right
    if (missing(T)) {
        T = 1
    }
    
    # how big are gulleys?
    if (missing(G)) {
        G = 0.5  # half the extent
    }
    
    if (sum(is.nan(M)) > 0) {
        stop("Error: Cost matrix includes NaNs")
    }
    
    if (min(M) < 0) {
    warning("Warning: cost matrix includes negative values; results may not be what you expect")
    }
    
    r <- nrow(M)
    c <- ncol(M)
    
    # Core cumulative cost calculation coded as mex
    D_phi <- dpcore(M, C)
    D <- D_phi$D
    phi <- D_phi$phi
    
    p <- NULL
    q <- NULL
    
    ## Traceback from top left?
    #i <- r
    #j <- c
    if (T == 0) {
        # Traceback from lowest cost "to edge" (gulleys)
        TE <- D[r,]
        RE <- D[,c]
        # eliminate points not in gulleys
        TE[1:round((1-G)*c)] <- max(D)
        RE[1:round((1-G)*r)] <- max(D)
        if (min(TE) < min(RE)) {
            i <- r
            j <- max(which(TE==min(TE)))
        } else {
            i <- max(which(RE==min(RE)))
            j <- c
        }
    } else {
        if (min(dim(D)) == 1) {
            # degenerate D has only one row or one column - messes up diag
            i <- r
            j <- c
        } else {
            # Traceback from min of antidiagonal
            #stepback = floor(0.1*c)
            stepback <- T
            DD = D[, c:1]
            slice <- DD[row(DD) == col(DD)+(r-stepback)]
            ii <- which.min(slice)
            i <- r - stepback + ii
            j <- c + 1 - ii
        }
    }
    
    p <- i
    q <- j
    sc <- M[p, q]
    
    while (i >= 1 && j >= 1) {
        if (i == 1 && j == 1) {
            break
        }
        #disp(paste0("i=",i," j=",j))
        tb <- phi[i, j]
        i <- i - C[tb, 1]
        j <- j - C[tb, 2]
        p <- c(i, p)
        q <- c(j, q)
        sc <- c(M[i, j], sc)
    }
    
    return(list(p=p, q=q, D=D, sc=sc))
}

In [11]:
# Test dpfast and dpcore
nrow = 10
ncol = 9
M = matrix(abs(rnorm(nrow * ncol)), nrow=nrow, ncol=ncol)
C = rbind(c(1, 1, 1), c(1, 0, 1), c(0, 1, 1))
dpfast(M, C)

$p
 [1]  1  2  3  4  5  6  6  7  8  8  9  9 10

$q
 [1] 1 1 1 1 1 2 3 4 5 6 7 8 9

$D
           [,1]      [,2]     [,3]     [,4]     [,5]     [,6]     [,7]     [,8]
 [1,] 0.2992151 0.3563219 1.083073 2.249643 2.304521 3.119489 3.783625 4.208435
 [2,] 0.7107260 0.8028231 1.508234 2.148663 2.398805 2.546784 3.647753 4.066733
 [3,] 0.9629494 1.7964953 1.794983 3.072016 2.766907 3.823903 2.690556 3.687542
 [4,] 1.8548705 1.6539032 2.083416 2.951520 2.939530 3.132848 2.808309 2.966334
 [5,] 2.2905538 2.9385026 2.892207 2.915463 5.139364 3.187943 3.720378 4.064328
 [6,] 3.5280922 2.3372800 2.616626 2.843955 4.107569 3.253231 4.625529 4.367052
 [7,] 3.7523601 2.5729866 4.095183 2.882764 3.202684 3.221840 4.018930 5.318242
 [8,] 4.1297558 3.1158748 3.133733 3.259466 2.893809 3.151147 4.405231 4.892192
 [9,] 4.2630921 3.5491851 3.568659 5.575097 3.834458 3.542819 3.923290 3.931661
[10,] 5.0672816 4.1986568 4.381228 4.363998 3.950284 3.661988 3.762335 4.643207
          [,9]
 [1,] 4.804694
 [2,] 4.186451
 [3,] 3.969716
 [4,] 4.422322
 [5,] 3.195353
 [6,] 4.191897
 [7,] 4.973756
 [8,] 5.668969
 [9,] 4.547651
[10,] 3.978241

$sc
 [1] 0.29921512 0.41151083 0.25222345 0.89192113 0.43568330 0.04672617
 [7] 0.27934628 0.26613736 0.01104548 0.25733838 0.77214219 0.00837096
[13] 0.04658030

In [127]:
sourceCpp("dist2.cpp")

In [128]:
x = matrix(c(1, 2, 3, 4, 5, 6), ncol = 3)
c = matrix(c(1, 2, 3), ncol = 3)
x
c

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2] [,3]
[1,] 1    2    3

In [129]:
dist2(x, c)

[,1]
[1,]  5  
[2,] 14

In [133]:
sourceCpp("dpcore_window.cpp")

In [134]:
dpcore_window(M, C, 4)

$D
           [,1]       [,2]      [,3]      [,4]      [,5]      [,6]      [,7]
 [1,] 0.2992151 0.35632189 1.0830726 2.2496432 2.3045207 0.0000000 0.0000000
 [2,] 0.7107260 0.80282309 1.5082336 2.1486632 2.3988045 0.2422635 0.0000000
 [3,] 0.9629494 1.79649531 1.7949835 3.0720157 2.7669065 1.6673619 0.1437715
 [4,] 1.8548705 1.65390324 2.0834163 2.9515205 2.9395300 2.0333030 0.2615251
 [5,] 2.2905538 2.93850259 2.8922073 2.9154635 5.1393638 2.2817156 1.1735934
 [6,] 0.0000000 0.04672617 0.3260725 0.5534011 1.8170155 1.8823037 2.6111797
 [7,] 0.0000000 0.00000000 1.7579031 0.5922098 0.9121300 0.9312864 1.7283760
 [8,] 0.0000000 0.00000000 0.0000000 0.3767027 0.3877482 0.6450866 1.8991697
 [9,] 0.0000000 0.00000000 0.0000000 0.0000000 0.9406492 1.0367583 1.4172288
[10,] 0.0000000 0.00000000 0.0000000 0.0000000 0.0000000 0.1191688 0.3386844
          [,8]      [,9]
 [1,] 0.000000 0.0000000
 [2,] 0.000000 0.0000000
 [3,] 0.000000 0.0000000
 [4,] 0.275778 0.0000000
 [5,] 1.517544 0.2290196
 [6,] 1.820268 1.2255635
 [7,] 3.027688 2.0074227
 [8,] 2.601638 2.7841993
 [9,] 1.425600 2.0415896
[10,] 1.219556 1.2661364

$phi
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,]    0    3    3    3    3    0    0    0    0
 [2,]    2    1    1    1    3    2    0    0    0
 [3,]    2    1    1    1    1    2    2    0    0
 [4,]    2    1    3    1    2    2    2    2    0
 [5,]    2    2    1    1    3    2    2    1    2
 [6,]    0    3    3    3    3    3    2    1    2
 [7,]    0    0    3    1    1    3    3    3    2
 [8,]    0    0    0    3    3    3    3    1    2
 [9,]    0    0    0    0    3    1    1    3    3
[10,]    0    0    0    0    0    3    3    3    3

$wss
[1] 4

#### 5. Shape Descriptors

In [12]:
calcDescriptor <- function(subsequence, descriptorName = "HOG1D", param = NULL) {
  if (length(dim(subsequence)) != 1) {
    stop("The input subsequence should be one-dimensional\n")
  }
  
  if (missing(param)) {
    param <- validateHOG1Dparam()
  }
  
  switch(descriptorName,
         "HOG1D" = {
           val_param <- validateHOG1Dparam(param)
           descriptor <- descriptorHOG1D(subsequence, val_param)
         },
         "PAA" = {
           val_param <- validatePAAdescriptorparam(param)
           descriptor <- descriptorPAA(subsequence, val_param)
         },
         "DWT" = {
           val_param <- validateDWTdescriptorparam(param)
           descriptor <- descriptorDWT(subsequence, val_param)
         },
         stop("Only support 3 descriptors\n")
  )
  
  return(descriptor)
}

#### 6. Validate Descriptor

In [13]:
validateDWTdescriptorparam <- function(param) {
    if (missing(param) || !is.list(param)) {
        val_param <- list(numLevels = 2, selection = 'Haar', n = 2)
        return(val_param)
    }
    
    val_param <- param
    if (!'numLevels' %in% names(param)) {
        val_param$numLevels <- 2
    }
    if (!'selection' %in% names(param)) {
        val_param$selection <- 'Haar'
    }
    
    if (!'n' %in% names(param)) {
        val_param$n <- 2
    }
    return(val_param)
}

In [14]:
validateHOG1Dparam <- function(param = NULL) {
  # a typical valid setting
  # {
  #   param.blocks    = [1 2];  # unit: cell
  #   param.cells     = [1 25]; # unit: t
  #   param.gradmethod = 'centered'; # 'centered'
  #   param.nbins = 8;
  #   param.sign = 'true';
  # }
  if (is.null(param) || !is.list(param)) {
    val_param <- list(
      # blocks = c(1, 2),
      cells = c(1, 25),
      overlap = 0,
      gradmethod = "centered",
      nbins = 8,
      sign = "true",
      xscale = 0.1
      # cutoff = c(2, 51)
    )
    return(val_param)
  }
  
  val_param <- param
  
  if (!("overlap" %in% names(val_param))) {
    val_param$overlap <- 12
  }
  
  if (!("xscale" %in% names(val_param))) {
    val_param$xscale <- 0.1
  }
  
  if (!("cells" %in% names(val_param))) {
    val_param$cells <- c(1, 25)
  }
  
  if (!("gradmethod" %in% names(val_param))) {
    val_param$gradmethod <- "uncentered"
  }
  
  if (!("nbins" %in% names(val_param))) {
    val_param$nbins <- 8
  }
  
  if (!("sign" %in% names(val_param))) {
    val_param$sign <- "true"
  }
  
  return(val_param)
}

In [15]:
# validate parameters of piecewise aggregate approximation
validatePAAparam <- function(param) {
  
  if (missing(param) || !is.list(param)) {
    val_param <- list(segNum = 10, segLen = NULL, priority = "segNum")
    return(val_param)
  }
  
  val_param <- list()
  
  if (!is.null(param$segNum)) {
    if (param$segNum > 0) {
      val_param$segNum <- param$segNum
    } else {
      val_param$segNum <- 10
    }
  } else {
    val_param$segNum <- 10
  }
  
  if (!is.null(param$segLen)) {
    if (param$segLen > 0) {
      val_param$segLen <- param$segLen
    } else {
      val_param$segLen <- 5
    }
  } else {
    val_param$segLen <- 5
  }
  
  if (!is.null(param$priority)) {
    val_param$priority <- param$priority
  } else {
    val_param$priority <- "segNum"
  }
  
  switch(val_param$priority,
         segNum = {
           if (is.null(val_param$segNum) || val_param$segNum <= 0) {
             val_param$segNum <- 10
           }
         },
         segLen = {
           if (is.null(val_param$segLen) || val_param$segLen <= 0) {
             val_param$segLen <- 5
           }
         },
         {
           val_param$priority <- "segNum"
           if (is.null(val_param$segNum) || val_param$segNum <= 0) {
             val_param$segNum <- 10
           }
         }
  )
  
  return(val_param)
}

validatePAAdescriptorparam <- function(param = NULL) {
  
  if (is.null(param) || !is.list(param)) {
    val_param <- list(segNum = 10, segLen = NULL, priority = "segNum")
    return(val_param)
  }
  
  val_param <- validatePAAparam(param)
  return(val_param)
  
}

#### 7. ShapeDTW

In [16]:
shapeDTW <- function(p, q, seqlen, descriptorSetting = NULL, metric = "Euclidean") {
  if (!is.vector(p) || !is.vector(q)) {
    stop("Only support univariate time series\n")
  }
  
  if (is.null(metric)) {
    metric <- "Euclidean"
  }
  
  p <- p %>% t() %>% as.data.frame()
  q <- q %>% t() %>% as.data.frame()
  
  lenp <- length(p)
  lenq <- length(q)
  
  if (is.null(descriptorSetting)) {
    hog <- validateHOG1Dparam()
    hog$cells <- c(1, round(seqlen/2)-1)
    hog$overlap <- 0
    hog$xscale <- 0.1
    
    paa <- validatePAAdescriptorparam()
    paa$priority <- "segNum"
    segNum <- ceiling(seqlen/5)
    paa$segNum <- segNum
    
    numLevels <- 3
    dwt <- validateDWTdescriptorparam()
    dwt$numLevels <- numLevels
    
    self <- NULL
    
    descriptorSetting <- list(method = "HOG1D", param = hog)
  }
  
  # First compute descriptor at each point, and transform the univariate time series to multivariate one
  p_subsequences <- samplingSequencesIdx(p, seqlen, 1:lenp)
  q_subsequences <- samplingSequencesIdx(q, seqlen, 1:lenq)
  
  # Descriptor
  descriptorName <- descriptorSetting$method
  descriptorParam <- descriptorSetting$param
  
  p_nsubsequences <- length(p_subsequences)
  p_descriptors <- vector("list", p_nsubsequences)
  for (j in 1:p_nsubsequences) {
    seq <- p_subsequences[[j]]
    p_descriptors[[j]] <- calcDescriptor(seq, descriptorName, descriptorParam)
  }
  p_descriptors <- do.call(rbind, p_descriptors)
  
  q_nsubsequences <- length(q_subsequences)
  q_descriptors <- vector("list", q_nsubsequences)
  for (j in 1:q_nsubsequences) {
    seq <- q_subsequences[[j]]
    q_descriptors[[j]] <- calcDescriptor(seq, descriptorName, descriptorParam)
  }
  q_descriptors <- do.call(rbind, q_descriptors)
  
  # Match multivariate time series 'p_descriptors' & 'q_descriptors'
  # Run DTW
  switch(metric,
         "Euclidean" = {
           d <- dist2(p_descriptors, q_descriptors)
           d <- sqrt(d)
         },
         "chi-square" = {
           d <- hist_cost_2(p_descriptors, q_descriptors)
         },
         stop("Only support two distance metrics\n")
  )
  
  dtw_res <- dpfast(d)
  
  idxp <- dtw_res[[1]]
  idxq <- dtw_res[[2]]
  cD <- dtw_res[[3]]
  pc <- dtw_res[[4]]
  
  match <- cbind(idxp, idxq)
  lPath <- length(idxp)
  distDescriptor <- sum(pc)
  
  # Compute distance using raw signals, instead of descriptor distances
  wp <- wpath2mat(idxp) %*% p
  wq <- wpath2mat(idxq) %*% q
  
  distRaw <- sum(sqrt((wp-wq)^2))
  
  return(list(distRaw = distRaw, distDescriptor = distDescriptor))
}